#if !canImport(ObjectiveC)
import XCTest

extension AtomicTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AtomicTests = [
        ("testAtomicWrite", testAtomicWrite),
    ]
}

extension RwLockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RwLockTests = [
        ("testMultipleReaders", testMultipleReaders),
        ("testMultipleWriters", testMultipleWriters),
    ]
}

extension SemaphoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SemaphoreTests = [
        ("testLocking", testLocking),
        ("testWith", testWith),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AtomicTests.__allTests__AtomicTests),
        testCase(RwLockTests.__allTests__RwLockTests),
        testCase(SemaphoreTests.__allTests__SemaphoreTests),
    ]
}
#endif
